services:

  #db:
  #  image: postgres:14.5
  #  restart: always
  #  volumes:
  #    - ./data/db:/var/lib/postgresql/data
  #  environment:
  #    - POSTGRES_DB=postgres
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=postgres
  
  cache:
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/cache:/data

  backend:
    build: .
    ports:
      - "8000:8000"
    command:  gunicorn --bind 0.0.0.0:8000 educa.wsgi:application
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - USE_S3=TRUE
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_STORAGE_BUCKET_NAME=educa-891662393497
    depends_on:
      #- db
      - cache
    
